name: Redeploy Terraform Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      message:
        default: 'Manual run'

permissions:
  contents: read
  id-token: write

jobs:
  redeploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::058264485635:role/GitHubActions-erictran0x-itg-stamdb
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Create terraform.tfvars
        working-directory: ./terraform
        run: |
          echo "opensearch_settings = {" > terraform.tfvars
          echo "  user = \"${{ secrets.OPENSEARCH_USER }}\"" >> terraform.tfvars
          echo "  pass = \"${{ secrets.OPENSEARCH_PASS }}\"" >> terraform.tfvars
          echo "  url  = \"${{ secrets.OPENSEARCH_URL }}\"" >> terraform.tfvars
          echo "}" >> terraform.tfvars
          echo "" >> terraform.tfvars
          echo "github_token = \"${{ secrets.MY_GITHUB_TOKEN }}\""

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Apply Terraform changes
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve